# Generated by Django 4.0.2 on 2022-04-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0005_remove_course_coursename_course_courseabbv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=300),
        ),
    ]
