# Generated by Django 4.0.2 on 2022-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0006_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
